from fastapi import APIRouter, Request, HTTPException
from fastapi.concurrency import run_in_threadpool
from pydantic import BaseModel, Field
import math
from typing import List, Tuple, Literal, Optional, Dict

from app.core.tokens import verify_token
from app.api.routes.auth import COOKIE_NAME
from app.services.auth_service import add_ledger, get_user_by_id
from app.core.config import settings
from app.engine.prints_engine import apply_design, apply_design_ai, ApplyIn

def _quad_from_placement(w: int, h: int, x: float, y: float, rw: float, rh: float, rotation_deg: float) -> List[Tuple[float, float]]:
    # placement comes normalized 0..1
    px = float(x) * w
    py = float(y) * h
    pw = float(rw) * w
    ph = float(rh) * h

    pw = max(1.0, pw)
    ph = max(1.0, ph)

    cx = px + pw / 2.0
    cy = py + ph / 2.0

    ang = float(rotation_deg or 0.0) * math.pi / 180.0
    c = math.cos(ang)
    s = math.sin(ang)

    corners = [(-pw/2, -ph/2), (pw/2, -ph/2), (pw/2, ph/2), (-pw/2, ph/2)]
    out: List[Tuple[float, float]] = []
    for dx, dy in corners:
        rx = dx * c - dy * s
        ry = dx * s + dy * c
        out.append((cx + rx, cy + ry))
    return out



router = APIRouter()

ApplyMode = str
def _uid(req: Request) -> str:
    tok = req.cookies.get(COOKIE_NAME)
    if not tok:
        raise HTTPException(status_code=401, detail="Not authenticated")
    v = verify_token(tok)
    uid = v[0] if v else None
    if not uid:
        raise HTTPException(status_code=401, detail="Invalid session")
    return uid


class Placement(BaseModel):
    # normalized (0..1) relative to base image size
    x: float
    y: float
    w: float
    h: float

class Warp(BaseModel):
    top: float = 0.0
    right: float = 0.0
    bottom: float = 0.0
    left: float = 0.0


class ApplyOptions(BaseModel):
    warp: Optional[Warp] = None
    rotationDeg: float = 0.0
    curve: float = 0.0  # -1..1 (UI bend preview), optional for engine
    placementLock: bool = True
    renderMode: str = "full"  # full | mask_only

class ApplyBody(BaseModel):
    baseUrl: str = Field(..., description="Absolute URL to base garment photo (usually /static/assets/..)")
    designUrl: str = Field(..., description="Absolute URL to design/logo image")
    mode: ApplyMode = Field("print_dtf", description="Application type")
    # Preferred (v2): normalized placement rect + optional rotation
    placement: Optional[Placement] = None
    options: Optional[ApplyOptions] = None
    # Back-compat (v1): quad in pixel coords
    quad: Optional[List[Tuple[float, float]]] = Field(None, description="4 points (x,y) in base-image pixel coords")
    note: Optional[str] = None
    # Idempotency key generated by frontend and persisted across reload/login.
    # If the same requestId is re-submitted, credits must NOT be charged again,
    # and (when available) the cached result is returned.
    requestId: Optional[str] = None

@router.post("/prints/apply")
async def prints_apply(req: Request, body: ApplyBody):
    """
    Print/Design v2 engine (deterministic, non-AI):
    - accepts either:
      (A) placement (normalized rect) + options.rotationDeg
      (B) quad (4 points in pixel coords)
    - warps design into quad (perspective), applies style by mode
    - saves PNG into /static/assets and returns URLs
    """
    uid = _uid(req)

    # Stable idempotency key for this apply attempt.
    # If frontend didn't pass it, we still generate one and return it,
    # but true idempotency across reloads requires frontend to persist requestId.
    import uuid
    request_id = (body.requestId or '').strip() or f"prn_{uuid.uuid4().hex}"

    # If we already have a cached successful result for this request, return it.
    try:
        from app.db.sqlite import get_prints_cache
        cached = get_prints_cache(uid, request_id)
        if cached:
            user_after = get_user_by_id(uid)
            bal_after = int((user_after or {}).get('credits') or 0)
            return {"ok": True, "balance": bal_after, "requestId": request_id, **cached}
    except Exception:
        # Cache is best-effort; never break apply.
        pass

    quad = body.quad

    if quad is None:
        if not body.placement:
            raise HTTPException(status_code=400, detail="Нужно указать placement или quad")
        rot = float(body.options.rotationDeg) if body.options else 0.0
        try:
            from app.engine.prints_engine import get_image_size
            bw, bh = get_image_size(body.baseUrl)
        except ValueError as e:
            raise HTTPException(status_code=400, detail=str(e))

        quad = _quad_from_placement(
            bw, bh,
            body.placement.x, body.placement.y,
            body.placement.w, body.placement.h,
            rot,
        )

    try:
        # spend 1 credit per apply (no debt)
        try:
            # IMPORTANT: use request_id as ledger ref for idempotency.
            add_ledger(uid, -1, "PRINTS_APPLY", ref=request_id)
        except ValueError as e:
            raise HTTPException(status_code=402, detail=str(e))

        placement_lock = bool(body.options.placementLock) if body.options else True

        # Gemini is the default renderer when configured.
        # placementLock is a HARD CONSTRAINT for geometry (the prompt must obey it),
        # NOT a switch to disable AI.
        use_ai = bool((settings.GEMINI_API_KEY or '').strip())

        inp = ApplyIn(
            base_url=body.baseUrl,
            design_url=body.designUrl,
            mode=body.mode,
            quad=quad,
            placement_lock=placement_lock,
            render_mode=((body.options.renderMode if body.options else 'full') or 'full'),
        )

        # optional UI warp (4 mid-handles) — passed through for engine
        try:
            if body.options and getattr(body.options, "warp", None) is not None:
                setattr(inp, 'warp', body.options.warp.model_dump())
        except Exception:
            pass

        # optional UI bend
        try:
            setattr(inp, 'curve', float(body.options.curve) if body.options else 0.0)
        except Exception:
            pass

        out = None
        if use_ai:
            try:
                out = await run_in_threadpool(apply_design_ai, inp)
            except Exception as e:
                # Fallback to deterministic overlay if AI fails (network/timeouts/etc.)
                import traceback
                print("prints/apply: AI failed → fallback overlay:", repr(e))
                traceback.print_exc()

        if out is None:
            out = await run_in_threadpool(apply_design, inp)

        # Save successful result to cache so reload/login won't rerun AI or re-spend.
        try:
            from app.db.sqlite import set_prints_cache
            set_prints_cache(uid, request_id, out)
        except Exception:
            pass
    except HTTPException:
        # Do not wrap HTTPExceptions into 500.
        raise
    except ValueError as e:
        # refund if we already spent
        try:
            add_ledger(uid, +1, "PRINTS_REFUND", ref=request_id)
        except Exception:
            pass
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        # refund if we already spent
        try:
            add_ledger(uid, +1, "PRINTS_REFUND", ref=request_id)
        except Exception:
            pass
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"prints_apply failed: {type(e).__name__}: {e}")

    user_after = get_user_by_id(uid)
    bal_after = int((user_after or {}).get('credits') or 0)
    return {"ok": True, "balance": bal_after, "requestId": request_id, **out}